import { mkdir, writeFile } from "node:fs/promises";
const cutoff=new Date(Date.now()-365*86400000).toISOString().slice(0,10);
const tradeSource="https://raw.githubusercontent.com/TattooedHead/house-stock-watcher-data/main/data/all_transactions.json";
const newsSource="https://news.google.com/rss/search?q=congressional+stock+trades+OR+government+official+financial+disclosure&hl=en-US&gl=US&ceid=US:en";
function dateOnly(value){const text=String(value||"");const m=text.match(/^(\d{2})\/(\d{2})\/(\d{4})$/);return m?m[3]+"-"+m[1]+"-"+m[2]:text.slice(0,10)}
function clean(value){return String(value||"").replace(/<[^>]+>/g,"").trim()}
function items(xml){return Array.from(xml.matchAll(/<item>([\s\S]*?)<\/item>/g)).map(m=>{function read(t){const r=new RegExp("<"+t+"[^>]*>([\s\S]*?)</"+t+">");return clean(m[1].match(r)?.[1])}return{title:read("title"),link:read("link"),description:read("description"),pubDate:read("pubDate")}})}
async function main(){const pair=await Promise.all([fetch(tradeSource),fetch(newsSource)]);if(!pair[0].ok||!pair[1].ok)throw new Error("Source request failed");const raw=await pair[0].json();const trades=raw.filter(x=>dateOnly(x.transaction_date)>=cutoff).map(x=>{const official=x.representative||x.owner||"Unknown official";const state=String(x.district||"").match(/^[A-Z]{2}/)?.[0]||"";return{official,party:x.party||"Unknown",state,employment:"current",ticker:x.ticker||"—",asset:x.asset_description||x.ticker||"Unspecified asset",type:String(x.type||"").toLowerCase().includes("sale")?"Sale":"Purchase",range:x.amount||"Not reported",amount:Number(x.amount_mid||0),transactionDate:dateOnly(x.transaction_date),disclosureDate:x.disclosure_date||"",status:"Verified",initials:official.split(/\s+/).map(y=>y[0]).join("").slice(0,2).toUpperCase(),sourceUrl:x.source_url||"https://disclosures-clerk.house.gov/FinancialDisclosure"}}).filter(x=>x.transactionDate);const news=items(await pair[1].text()).map((x,i)=>{const d=new Date(x.pubDate);return{id:"feed-"+d.getTime()+"-"+i,source:(x.title.match(/ - ([^-]+)$/)?.[1]||"PUBLIC NEWS").toUpperCase(),date:d.toISOString().slice(0,10),category:/ethic|disclosure|filing/i.test(x.title+x.description)?"Government":/policy|congress|senate|house/i.test(x.title+x.description)?"Policy & markets":"Markets",relevance:Math.max(1,100-i),title:x.title.replace(/ - [^-]+$/,""),summary:x.description||"Publicly available news related to government disclosures and markets.",originalUrl:x.link}}).filter(x=>x.date>=cutoff);await mkdir("data",{recursive:true});await writeFile("data/trades.json",JSON.stringify(trades,null,2));await writeFile("data/news.json",JSON.stringify(news,null,2));await writeFile("data/metadata.json",JSON.stringify({generatedAt:new Date().toISOString(),coverageStart:cutoff,coverageEnd:new Date().toISOString().slice(0,10),tradeCount:trades.length,newsCount:news.length,tradeSource,newsSource},null,2));console.log("Generated "+trades.length+" trades and "+news.length+" news stories")}
main().catch(e=>{console.error(e);process.exitCode=1})
